import { Calendar, MapPin, Star, Users } from 'lucide-react';

export const featuredCategories = [
  { name: 'Salão de Beleza', count: '1.2K+', icon: '💄' },
  { name: 'Barbearia', count: '890', icon: '✂️' },
  { name: 'Spa & Massagem', count: '450', icon: '🧘‍♀️' },
  { name: 'Odontologia', count: '320', icon: '🦷' },
  { name: 'Personal Trainer', count: '760', icon: '💪' },
  { name: 'Estética', count: '540', icon: '✨' },
  { name: 'Manicure', count: '680', icon: '💅' },
  { name: 'Psicologia', count: '420', icon: '🧠' },
  { name: 'Nutrição', count: '380', icon: '🥗' },
  { name: 'Fisioterapia', count: '510', icon: '🏥' },
  { name: 'Pilates', count: '290', icon: '🤸‍♀️' },
  { name: 'Tatuagem', count: '340', icon: '🎨' },
  { name: 'Pet Shop', count: '620', icon: '🐶' },
  { name: 'Fotografia', count: '280', icon: '📸' },
  { name: 'Mecânica', count: '450', icon: '🔧' },
  { name: 'Limpeza', count: '590', icon: '🧹' },
  { name: 'Advocacia', count: '310', icon: '⚖️' },
  { name: 'Contabilidade', count: '270', icon: '📊' },
  { name: 'Academia', count: '720', icon: '🏋️' },
  { name: 'Yoga', count: '330', icon: '🧘' },
  { name: 'Veterinário', count: '410', icon: '🩺' },
  { name: 'Dermatologia', count: '390', icon: '💆' },
  { name: 'Consultoria', count: '260', icon: '💼' },
  { name: 'Design', count: '350', icon: '🎨' },
  { name: 'Marketing', count: '300', icon: '📱' },
  { name: 'Carpintaria', count: '240', icon: '🪵' },
  { name: 'Jardinagem', count: '370', icon: '🌱' },
  { name: 'Eletricista', count: '490', icon: '⚡' },
  { name: 'Encanador', count: '460', icon: '🔩' },
  { name: 'Pintura', count: '380', icon: '🎨' },
];

export const stats = [
  {
    label: 'Agendamentos hoje',
    value: '2.4K',
    icon: Calendar,
    color: 'text-blue-600',
  },
  {
    label: 'Profissionais ativos',
    value: '3.2K',
    icon: Users,
    color: 'text-green-600',
  },
  { label: 'Cidades', value: '150+', icon: MapPin, color: 'text-purple-600' },
  { label: 'Avaliação', value: '4.9', icon: Star, color: 'text-yellow-600' },
];
