/**
 * Supported countries in the platform
 * ISO 3166-1 alpha-2 country codes
 */

import type { TCurrencyCode } from './currencies';

export interface ICountry {
  code: string;
  name: string;
  nativeName: string;
  currency: TCurrencyCode;
  locale: string;
  phoneCode: string;
  phoneFormat: string; // Mask format using # for digits
  postalCodeFormat: string; // Regex pattern
  postalCodeMask: string; // Mask format
  postalCodeLabel: string; // Label for the postal code field
  stateLabel: string; // Label for state/province field
  states?: { code: string; name: string }[];
  timezone: string; // Default timezone
}

export const COUNTRIES = {
  // América do Sul
  BR: {
    code: 'BR',
    name: 'Brazil',
    nativeName: 'Brasil',
    currency: 'BRL',
    locale: 'pt-BR',
    phoneCode: '+55',
    phoneFormat: '(##) #####-####',
    postalCodeFormat: '^\\d{5}-?\\d{3}$',
    postalCodeMask: '#####-###',
    postalCodeLabel: 'CEP',
    stateLabel: 'Estado',
    timezone: 'America/Sao_Paulo',
    states: [
      { code: 'AC', name: 'Acre' },
      { code: 'AL', name: 'Alagoas' },
      { code: 'AP', name: 'Amapá' },
      { code: 'AM', name: 'Amazonas' },
      { code: 'BA', name: 'Bahia' },
      { code: 'CE', name: 'Ceará' },
      { code: 'DF', name: 'Distrito Federal' },
      { code: 'ES', name: 'Espírito Santo' },
      { code: 'GO', name: 'Goiás' },
      { code: 'MA', name: 'Maranhão' },
      { code: 'MT', name: 'Mato Grosso' },
      { code: 'MS', name: 'Mato Grosso do Sul' },
      { code: 'MG', name: 'Minas Gerais' },
      { code: 'PA', name: 'Pará' },
      { code: 'PB', name: 'Paraíba' },
      { code: 'PR', name: 'Paraná' },
      { code: 'PE', name: 'Pernambuco' },
      { code: 'PI', name: 'Piauí' },
      { code: 'RJ', name: 'Rio de Janeiro' },
      { code: 'RN', name: 'Rio Grande do Norte' },
      { code: 'RS', name: 'Rio Grande do Sul' },
      { code: 'RO', name: 'Rondônia' },
      { code: 'RR', name: 'Roraima' },
      { code: 'SC', name: 'Santa Catarina' },
      { code: 'SP', name: 'São Paulo' },
      { code: 'SE', name: 'Sergipe' },
      { code: 'TO', name: 'Tocantins' },
    ],
  },
  AR: {
    code: 'AR',
    name: 'Argentina',
    nativeName: 'Argentina',
    currency: 'ARS',
    locale: 'es-AR',
    phoneCode: '+54',
    phoneFormat: '(###) ###-####',
    postalCodeFormat: '^[A-Z]?\\d{4}[A-Z]{0,3}$',
    postalCodeMask: '####',
    postalCodeLabel: 'Código Postal',
    stateLabel: 'Provincia',
    timezone: 'America/Argentina/Buenos_Aires',
  },
  CL: {
    code: 'CL',
    name: 'Chile',
    nativeName: 'Chile',
    currency: 'CLP',
    locale: 'es-CL',
    phoneCode: '+56',
    phoneFormat: '# #### ####',
    postalCodeFormat: '^\\d{7}$',
    postalCodeMask: '#######',
    postalCodeLabel: 'Código Postal',
    stateLabel: 'Región',
    timezone: 'America/Santiago',
  },
  CO: {
    code: 'CO',
    name: 'Colombia',
    nativeName: 'Colombia',
    currency: 'COP',
    locale: 'es-CO',
    phoneCode: '+57',
    phoneFormat: '### ### ####',
    postalCodeFormat: '^\\d{6}$',
    postalCodeMask: '######',
    postalCodeLabel: 'Código Postal',
    stateLabel: 'Departamento',
    timezone: 'America/Bogota',
  },
  PE: {
    code: 'PE',
    name: 'Peru',
    nativeName: 'Perú',
    currency: 'PEN',
    locale: 'es-PE',
    phoneCode: '+51',
    phoneFormat: '### ### ###',
    postalCodeFormat: '^\\d{5}$',
    postalCodeMask: '#####',
    postalCodeLabel: 'Código Postal',
    stateLabel: 'Departamento',
    timezone: 'America/Lima',
  },

  // América do Norte
  US: {
    code: 'US',
    name: 'United States',
    nativeName: 'United States',
    currency: 'USD',
    locale: 'en-US',
    phoneCode: '+1',
    phoneFormat: '(###) ###-####',
    postalCodeFormat: '^\\d{5}(-\\d{4})?$',
    postalCodeMask: '#####',
    postalCodeLabel: 'ZIP Code',
    stateLabel: 'State',
    timezone: 'America/New_York',
    states: [
      { code: 'AL', name: 'Alabama' },
      { code: 'AK', name: 'Alaska' },
      { code: 'AZ', name: 'Arizona' },
      { code: 'AR', name: 'Arkansas' },
      { code: 'CA', name: 'California' },
      { code: 'CO', name: 'Colorado' },
      { code: 'CT', name: 'Connecticut' },
      { code: 'DE', name: 'Delaware' },
      { code: 'FL', name: 'Florida' },
      { code: 'GA', name: 'Georgia' },
      { code: 'HI', name: 'Hawaii' },
      { code: 'ID', name: 'Idaho' },
      { code: 'IL', name: 'Illinois' },
      { code: 'IN', name: 'Indiana' },
      { code: 'IA', name: 'Iowa' },
      { code: 'KS', name: 'Kansas' },
      { code: 'KY', name: 'Kentucky' },
      { code: 'LA', name: 'Louisiana' },
      { code: 'ME', name: 'Maine' },
      { code: 'MD', name: 'Maryland' },
      { code: 'MA', name: 'Massachusetts' },
      { code: 'MI', name: 'Michigan' },
      { code: 'MN', name: 'Minnesota' },
      { code: 'MS', name: 'Mississippi' },
      { code: 'MO', name: 'Missouri' },
      { code: 'MT', name: 'Montana' },
      { code: 'NE', name: 'Nebraska' },
      { code: 'NV', name: 'Nevada' },
      { code: 'NH', name: 'New Hampshire' },
      { code: 'NJ', name: 'New Jersey' },
      { code: 'NM', name: 'New Mexico' },
      { code: 'NY', name: 'New York' },
      { code: 'NC', name: 'North Carolina' },
      { code: 'ND', name: 'North Dakota' },
      { code: 'OH', name: 'Ohio' },
      { code: 'OK', name: 'Oklahoma' },
      { code: 'OR', name: 'Oregon' },
      { code: 'PA', name: 'Pennsylvania' },
      { code: 'RI', name: 'Rhode Island' },
      { code: 'SC', name: 'South Carolina' },
      { code: 'SD', name: 'South Dakota' },
      { code: 'TN', name: 'Tennessee' },
      { code: 'TX', name: 'Texas' },
      { code: 'UT', name: 'Utah' },
      { code: 'VT', name: 'Vermont' },
      { code: 'VA', name: 'Virginia' },
      { code: 'WA', name: 'Washington' },
      { code: 'WV', name: 'West Virginia' },
      { code: 'WI', name: 'Wisconsin' },
      { code: 'WY', name: 'Wyoming' },
      { code: 'DC', name: 'District of Columbia' },
    ],
  },
  MX: {
    code: 'MX',
    name: 'Mexico',
    nativeName: 'México',
    currency: 'MXN',
    locale: 'es-MX',
    phoneCode: '+52',
    phoneFormat: '## #### ####',
    postalCodeFormat: '^\\d{5}$',
    postalCodeMask: '#####',
    postalCodeLabel: 'Código Postal',
    stateLabel: 'Estado',
    timezone: 'America/Mexico_City',
  },

  // Europa
  PT: {
    code: 'PT',
    name: 'Portugal',
    nativeName: 'Portugal',
    currency: 'EUR',
    locale: 'pt-PT',
    phoneCode: '+351',
    phoneFormat: '### ### ###',
    postalCodeFormat: '^\\d{4}-\\d{3}$',
    postalCodeMask: '####-###',
    postalCodeLabel: 'Código Postal',
    stateLabel: 'Distrito',
    timezone: 'Europe/Lisbon',
  },
  ES: {
    code: 'ES',
    name: 'Spain',
    nativeName: 'España',
    currency: 'EUR',
    locale: 'es-ES',
    phoneCode: '+34',
    phoneFormat: '### ## ## ##',
    postalCodeFormat: '^\\d{5}$',
    postalCodeMask: '#####',
    postalCodeLabel: 'Código Postal',
    stateLabel: 'Provincia',
    timezone: 'Europe/Madrid',
  },
  FR: {
    code: 'FR',
    name: 'France',
    nativeName: 'France',
    currency: 'EUR',
    locale: 'fr-FR',
    phoneCode: '+33',
    phoneFormat: '# ## ## ## ##',
    postalCodeFormat: '^\\d{5}$',
    postalCodeMask: '#####',
    postalCodeLabel: 'Code Postal',
    stateLabel: 'Région',
    timezone: 'Europe/Paris',
  },
  DE: {
    code: 'DE',
    name: 'Germany',
    nativeName: 'Deutschland',
    currency: 'EUR',
    locale: 'de-DE',
    phoneCode: '+49',
    phoneFormat: '#### #######',
    postalCodeFormat: '^\\d{5}$',
    postalCodeMask: '#####',
    postalCodeLabel: 'Postleitzahl',
    stateLabel: 'Bundesland',
    timezone: 'Europe/Berlin',
  },
  IT: {
    code: 'IT',
    name: 'Italy',
    nativeName: 'Italia',
    currency: 'EUR',
    locale: 'it-IT',
    phoneCode: '+39',
    phoneFormat: '### ### ####',
    postalCodeFormat: '^\\d{5}$',
    postalCodeMask: '#####',
    postalCodeLabel: 'CAP',
    stateLabel: 'Provincia',
    timezone: 'Europe/Rome',
  },
  NL: {
    code: 'NL',
    name: 'Netherlands',
    nativeName: 'Nederland',
    currency: 'EUR',
    locale: 'nl-NL',
    phoneCode: '+31',
    phoneFormat: '## ### ####',
    postalCodeFormat: '^\\d{4}\\s?[A-Z]{2}$',
    postalCodeMask: '#### AA',
    postalCodeLabel: 'Postcode',
    stateLabel: 'Provincie',
    timezone: 'Europe/Amsterdam',
  },
  GB: {
    code: 'GB',
    name: 'United Kingdom',
    nativeName: 'United Kingdom',
    currency: 'GBP',
    locale: 'en-GB',
    phoneCode: '+44',
    phoneFormat: '#### ######',
    postalCodeFormat: '^[A-Z]{1,2}\\d[A-Z\\d]?\\s?\\d[A-Z]{2}$',
    postalCodeMask: 'AA## #AA',
    postalCodeLabel: 'Postcode',
    stateLabel: 'County',
    timezone: 'Europe/London',
  },
  IE: {
    code: 'IE',
    name: 'Ireland',
    nativeName: 'Ireland',
    currency: 'EUR',
    locale: 'en-IE',
    phoneCode: '+353',
    phoneFormat: '## ### ####',
    postalCodeFormat: '^[A-Z\\d]{3}\\s?[A-Z\\d]{4}$',
    postalCodeMask: 'A## A#A#',
    postalCodeLabel: 'Eircode',
    stateLabel: 'County',
    timezone: 'Europe/Dublin',
  },
  BE: {
    code: 'BE',
    name: 'Belgium',
    nativeName: 'België',
    currency: 'EUR',
    locale: 'nl-BE',
    phoneCode: '+32',
    phoneFormat: '### ## ## ##',
    postalCodeFormat: '^\\d{4}$',
    postalCodeMask: '####',
    postalCodeLabel: 'Postcode',
    stateLabel: 'Province',
    timezone: 'Europe/Brussels',
  },
  AT: {
    code: 'AT',
    name: 'Austria',
    nativeName: 'Österreich',
    currency: 'EUR',
    locale: 'de-AT',
    phoneCode: '+43',
    phoneFormat: '### ### ####',
    postalCodeFormat: '^\\d{4}$',
    postalCodeMask: '####',
    postalCodeLabel: 'PLZ',
    stateLabel: 'Bundesland',
    timezone: 'Europe/Vienna',
  },
} as const satisfies Record<string, ICountry>;

export type TCountryCode = keyof typeof COUNTRIES;

export const COUNTRY_CODES = Object.keys(COUNTRIES) as TCountryCode[];

export const getCountry = (code: TCountryCode): ICountry => COUNTRIES[code];

export const getCountriesByRegion = () => ({
  southAmerica: ['BR', 'AR', 'CL', 'CO', 'PE'] as TCountryCode[],
  northAmerica: ['US', 'MX'] as TCountryCode[],
  europe: [
    'PT',
    'ES',
    'FR',
    'DE',
    'IT',
    'NL',
    'GB',
    'IE',
    'BE',
    'AT',
  ] as TCountryCode[],
});

export const getCountryOptions = () =>
  COUNTRY_CODES.map((code) => ({
    value: code,
    label: COUNTRIES[code].nativeName,
    flag: code.toLowerCase(),
  }));
