import type { IStore } from '@/types/api/stores.types';
import { IProfessional } from '@/types/api/users.types';

export const INITIAL_STORE: IStore = {
  id: '',
  name: '',
  description: '',
  country: 'BR',
  currency: 'BRL',
  timezone: 'America/Sao_Paulo',
  address: '',
  city: '',
  state: '',
  zipCode: '',
  telephone: '',
  email: '',
  isActive: true,
  amenities: [],
  website: '',
  instagram: '',
  facebook: '',
  gallery: [],
  storeMembers: [],
  services: [],
  schedules: [],
  openTime: '09:00',
  closeTime: '18:00',
  lunchStartTime: '12:00',
  lunchEndTime: '13:00',
  businessDays: {
    monday: false,
    tuesday: false,
    wednesday: false,
    thursday: false,
    friday: false,
    saturday: false,
    sunday: false,
  },
  notificationsHistory: [],
  notificationsSettings: {} as IStore['notificationsSettings'],
  reviews: [],
};

export const INITIAL_PROFESSIONAL: IProfessional = {
  id: '',
  user: {
    id: '',
    email: '',
    firstName: '',
    lastName: '',
    telephone: '',
    avatar: '',
    favorites: [],
    schedules: [],
    createdAt: new Date(),
  },
  role: 'professional',
  createdAt: new Date(),
  isActive: true,
  blockedTimes: [],
  services: [],
  schedules: [],
};

export const MOCK_STORES: IStore[] = [
  {
    id: '1',
    name: 'Loja Centro',
    description: 'Loja de roupas de alta qualidade',
    country: 'BR',
    currency: 'BRL',
    timezone: 'America/Sao_Paulo',
    address: 'Rua das Flores, 123',
    city: 'São Paulo',
    state: 'SP',
    zipCode: '01310-100',
    telephone: '(11) 3456-7890',
    email: 'centro@salao.com',
    isActive: true,
    amenities: [],
    website: '',
    instagram: '',
    facebook: '',
    storeMembers: [],
    gallery: [
      {
        id: '1',
        url: 'https://images.unsplash.com/photo-1611211235015-e2e3a7d09e97?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxiZWF1dHklMjBzYWxvbiUyMGludGVyaW9yJTIwbW9kZXJufGVufDF8fHx8MTc1OTc2MDI0N3ww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
        isMain: true,
      },
      {
        id: '2',
        url: 'https://images.unsplash.com/photo-1629881544138-c45fc917eb81?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxiYXJiZXJzaG9wJTIwY2hhaXJzfGVufDF8fHx8MTc1OTc5NDQ2OHww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
        isMain: false,
      },
      {
        id: '3',
        url: 'https://images.unsplash.com/photo-1600948836101-f9ffda59d250?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxoYWlyJTIwc2Fsb24lMjBpbnRlcmlvcnxlbnwxfHx8fDE3NTk2NzM0OTh8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
        isMain: false,
      },
      {
        id: '4',
        url: 'https://images.unsplash.com/photo-1662519951774-e8f89ea1200a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzcGElMjB0cmVhdG1lbnQlMjByb29tfGVufDF8fHx8MTc1OTczNDU5Nnww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
        isMain: false,
      },
    ],
    services: [],
    schedules: [],
    businessDays: {
      monday: false,
      tuesday: false,
      wednesday: false,
      thursday: false,
      friday: false,
      saturday: false,
      sunday: false,
    },
    openTime: '09:00',
    closeTime: '18:00',
    lunchStartTime: '12:00',
    lunchEndTime: '13:00',
  },
  {
    id: '2',
    name: 'Loja Shopping',
    description: 'Loja de roupas de alta qualidade',
    country: 'BR',
    currency: 'BRL',
    timezone: 'America/Sao_Paulo',
    address: 'Shopping Center, Loja 45',
    city: 'São Paulo',
    state: 'SP',
    zipCode: '04543-900',
    telephone: '(11) 3456-7891',
    email: 'shopping@salao.com',
    isActive: true,
    amenities: [],
    website: '',
    instagram: '',
    facebook: '',
    gallery: [
      {
        id: '1',
        url: 'https://images.unsplash.com/photo-1611211235015-e2e3a7d09e97?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxiZWF1dHklMjBzYWxvbiUyMGludGVyaW9yJTIwbW9kZXJufGVufDF8fHx8MTc1OTc2MDI0N3ww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
        isMain: true,
      },
      {
        id: '2',
        url: 'https://images.unsplash.com/photo-1629881544138-c45fc917eb81?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxiYXJiZXJzaG9wJTIwY2hhaXJzfGVufDF8fHx8MTc1OTc5NDQ2OHww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
        isMain: false,
      },
      {
        id: '3',
        url: 'https://images.unsplash.com/photo-1600948836101-f9ffda59d250?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxoYWlyJTIwc2Fsb24lMjBpbnRlcmlvcnxlbnwxfHx8fDE3NTk2NzM0OTh8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
        isMain: false,
      },
    ],
    storeMembers: [],
    services: [],
    schedules: [],
    businessDays: {
      monday: false,
      tuesday: false,
      wednesday: false,
      thursday: false,
      friday: false,
      saturday: false,
      sunday: false,
    },
    openTime: '09:00',
    closeTime: '18:00',
    lunchStartTime: '12:00',
    lunchEndTime: '13:00',
  },
  {
    id: '3',
    name: 'Loja Zona Sul',
    description: 'Loja de roupas de alta qualidade',
    country: 'BR',
    currency: 'BRL',
    timezone: 'America/Sao_Paulo',
    address: 'Av. Principal, 567',
    city: 'São Paulo',
    state: 'SP',
    zipCode: '04567-000',
    telephone: '(11) 3456-7892',
    email: 'zonasul@salao.com',
    isActive: false,
    amenities: [],
    website: '',
    instagram: '',
    facebook: '',
    gallery: [
      {
        id: '1',
        url: 'https://images.unsplash.com/photo-1611211235015-e2e3a7d09e97?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxiZWF1dHklMjBzYWxvbiUyMGludGVyaW9yJTIwbW9kZXJufGVufDF8fHx8MTc1OTc2MDI0N3ww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
        isMain: true,
      },
      {
        id: '2',
        url: 'https://images.unsplash.com/photo-1629881544138-c45fc917eb81?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxiYXJiZXJzaG9wJTIwY2hhaXJzfGVufDF8fHx8MTc1OTc5NDQ2OHww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
        isMain: false,
      },
      {
        id: '3',
        url: 'https://images.unsplash.com/photo-1600948836101-f9ffda59d250?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxoYWlyJTIwc2Fsb24lMjBpbnRlcmlvcnxlbnwxfHx8fDE3NTk2NzM0OTh8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
        isMain: false,
      },
    ],
    storeMembers: [],
    services: [],
    schedules: [],
    businessDays: {
      monday: false,
      tuesday: false,
      wednesday: false,
      thursday: false,
      friday: false,
      saturday: false,
      sunday: false,
    },
    openTime: '09:00',
    closeTime: '18:00',
    lunchStartTime: '12:00',
    lunchEndTime: '13:00',
  },
];
